<?php

namespace ES\AgendaBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use \DateTime;
use \DateInterval;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByMonth(int $month)
	{
		$qb = $this->createQueryBuilder('e');

		$date_from = new DateTime();
		$date_to = new DateTime();
		if ($month>0) {
			$interval = new DateInterval('P'.$month.'M');
			$date_from->add($interval);
			$date_to->add($interval);
		}
		if ($month<0) {
			$interval = new DateInterval('P'.(0-$month).'M');
			$date_from->sub($interval);
			$date_to->sub($interval);
		}

		$date_from = $date_from->modify('first day of this month')->setTime(0,0,0);
		$date_to = $date_to->modify('last day of this month')->setTime(23,59,59);

		$qb->setParameter('date_from', $date_from, \Doctrine\DBAL\Types\Type::DATETIME);
		$qb->setParameter('date_to', $date_to, \Doctrine\DBAL\Types\Type::DATETIME);
		$qb->andWhere($qb->expr()->between('e.dateBeginning', ':date_from', ':date_to'));
		$qb->orderBy('e.dateBeginning');
		return $qb->getQuery()->getResult();
	}
}
