es_user_home:
    path:      /list
    defaults:  
        _controller: ESUserBundle:User:index 
        page: 1
    requirements:
        page: \d*

es_user_view:
    path:      /{id}
    defaults: 
        _controller: ESUserBundle:User:view 
    requirements:
        id: \d+

es_user_become_author:
    path:      /author/{id}
    defaults: 
        _controller: ESUserBundle:User:becomeAuthor
    requirements:
        id: \d+

es_user_become_membre:
    path:      /membre/{id}
    defaults:
        _controller: ESUserBundle:User:becomeMembre
    requirements:
        id: \d+

es_user_delete_author:
    path:      /dauthor/{id}
    defaults:
        _controller: ESUserBundle:User:deleteAuthor
    requirements:
        id: \d+

es_user_delete_membre:
    path:      /dmembre/{id}
    defaults:
        _controller: ESUserBundle:User:deleteMembre
    requirements:
        id: \d+